# Generated by Django 4.0.4 on 2022-05-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='projectComponents',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='workingScope',
        ),
    ]
