# Generated by Django 4.0.4 on 2022-05-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('engineering', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.contract'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.projecttype'),
        ),
        migrations.AddField(
            model_name='moodboardpartimages',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='engineering.moodboardpart'),
        ),
        migrations.AddField(
            model_name='moodboardpart',
            name='moodBoardParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.moodboard'),
        ),
        migrations.AddField(
            model_name='moodboardpart',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.stylemoodboardpart'),
        ),
        migrations.AddField(
            model_name='moodboardpart',
            name='tableItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.itemstable'),
        ),
        migrations.AddField(
            model_name='moodboard',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.project'),
        ),
        migrations.AddField(
            model_name='moodboard',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineering.designtype'),
        ),
    ]
